# Spring properties
spring:
  application:
     name: accounts-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
    port: ${PORT:3333}
 
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
 
ribbon:
    eureka:
        enabled: true